### PR TITLE
chore: Ensure tests run in Release configuration

### PR DESCRIPTION
**Pull request by tomkerkhove**
Link: https://msazure.visualstudio.com/One/_workitems/edit/29935605

### CODE REVIEW

**Review by DeagleGross — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Works 🎉

image

**Comment by tomkerkhove** [comment]
@maksimkim Shall we already merge this one (force merge, don't have permissions) as we work on the fixes?

**Comment by tomkerkhove** [comment]
This is done as part of https://github.com/maksimkim/SpanNetty/pull/51 with these commits

**Pull request closed without merging**
